// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALURAtZP3l1py9TPSgSJ2c0jliTastthI',
    appId: '1:504746904982:web:86bde7d86f53df0ded21b7',
    messagingSenderId: '504746904982',
    projectId: 'ritmo-2da74',
    authDomain: 'ritmo-2da74.firebaseapp.com',
    storageBucket: 'ritmo-2da74.firebasestorage.app',
    measurementId: 'G-DQ33EMLYDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQuN3FyqKVNS-Ui1YlKJMYxxAN0x7rVG0',
    appId: '1:504746904982:android:99f0ce5805ba7088ed21b7',
    messagingSenderId: '504746904982',
    projectId: 'ritmo-2da74',
    storageBucket: 'ritmo-2da74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf9ZFf9KQDU_YDERb_nQzDDRcatyW8zZQ',
    appId: '1:504746904982:ios:45dd9d4e63fb764eed21b7',
    messagingSenderId: '504746904982',
    projectId: 'ritmo-2da74',
    storageBucket: 'ritmo-2da74.firebasestorage.app',
    iosBundleId: 'com.example.ritmoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf9ZFf9KQDU_YDERb_nQzDDRcatyW8zZQ',
    appId: '1:504746904982:ios:45dd9d4e63fb764eed21b7',
    messagingSenderId: '504746904982',
    projectId: 'ritmo-2da74',
    storageBucket: 'ritmo-2da74.firebasestorage.app',
    iosBundleId: 'com.example.ritmoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALURAtZP3l1py9TPSgSJ2c0jliTastthI',
    appId: '1:504746904982:web:a4f1bab3f7a1a895ed21b7',
    messagingSenderId: '504746904982',
    projectId: 'ritmo-2da74',
    authDomain: 'ritmo-2da74.firebaseapp.com',
    storageBucket: 'ritmo-2da74.firebasestorage.app',
    measurementId: 'G-TC0GH2JJGS',
  );
}
